// <auto-generated />
using Microsoft.Azure.Devices.ProtocolGateway.StorageClient.Implementation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Microsoft.Azure.Devices.ProtocolGateway.StorageClient.Implementation.Migrations
{
    [DbContext(typeof(DeviceContext))]
    [Migration("20171120001107_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.Azure.Devices.ProtocolGateway.StorageClient.Implementation.Models.Device", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeviceID");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Microsoft.Azure.Devices.ProtocolGateway.StorageClient.Implementation.Models.IncommingMessage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<int?>("FromDeviceID");

                    b.HasKey("ID");

                    b.HasIndex("FromDeviceID");

                    b.ToTable("Incomming");
                });

            modelBuilder.Entity("Microsoft.Azure.Devices.ProtocolGateway.StorageClient.Implementation.Models.OutgoingMessage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<int?>("ToDeviceID");

                    b.HasKey("ID");

                    b.HasIndex("ToDeviceID");

                    b.ToTable("Outgoing");
                });

            modelBuilder.Entity("Microsoft.Azure.Devices.ProtocolGateway.StorageClient.Implementation.Models.IncommingMessage", b =>
                {
                    b.HasOne("Microsoft.Azure.Devices.ProtocolGateway.StorageClient.Implementation.Models.Device", "FromDevice")
                        .WithMany()
                        .HasForeignKey("FromDeviceID");
                });

            modelBuilder.Entity("Microsoft.Azure.Devices.ProtocolGateway.StorageClient.Implementation.Models.OutgoingMessage", b =>
                {
                    b.HasOne("Microsoft.Azure.Devices.ProtocolGateway.StorageClient.Implementation.Models.Device", "ToDevice")
                        .WithMany()
                        .HasForeignKey("ToDeviceID");
                });
#pragma warning restore 612, 618
        }
    }
}
